name = "cds_dvtool"
version = "1.0.0"
description = "CDS Data Validation Tool"
authors = ["Kenneth Okeke <okekekenchi0802@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"

[cookies]
password="2IblL5LalKLT__9bOd0ujFQpIql3zPxSV965tRZqkFY"



